name: Combine package lists

on:
  push:
    branches: ["main"]
    paths:
      - "foreign-android-apps/categories/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate output yml file
        run: |
          mkdir -p output
          > output/raw.txt

          # collect all txt files from your folder
          find foreign-android-apps/categories -name "*.txt" -exec cat {} + > output/raw.txt

          # clean + deduplicate
          cat output/raw.txt \
            | sed 's/\r//' \
            | sed '/^\s*$/d' \
            | sort \
            | uniq \
            > output/clean.txt

          # Build yml
          {
            echo "include-package:"
            sed 's/^/- /' output/clean.txt
          } > foreign-android-apps/include-android-apps-tun.yml

          # Build inline array yml
          {
            printf "include-package: [ "
            paste -sd',' output/clean.txt | sed 's/\([^,]*\)/"\1"/g' | tr -d '\n'
            printf " ]\n"
          } > foreign-android-apps/include-android-apps-tun-inline.yml

      - name: Show result
        run: |
          echo "Generated file:"
          cat foreign-android-apps/include-android-apps-tun.yml

      - name: Commit file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add foreign-android-apps/include-android-apps-tun.yml
          git add foreign-android-apps/include-android-apps-tun-inline.yml
          git commit -m "Update output files" || exit 0
          git push
